name: Python CI

on:
  push:
    branches:
      - main  # Или другая ветка, если нужно
  pull_request:
    branches:
      - main  # Для PR в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Вы можете выбрать другую ОС, например, windows-latest или macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run tests
        run: |
          pytest  

